name: Build

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle build
        run: ./gradlew build

      - name: Gradle publish
        run: ./gradlew publishToMavenLocal

      - name: Archive distributions
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ~/.m2/repository/com/github/jakemarsden/water-sort-puzzle/*
            !~/.m2/repository/com/github/jakemarsden/water-sort-puzzle/**/maven-metadata-local.xml
          if-no-files-found: error

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results
          path: build/test-results/**/TEST-*.xml
          if-no-files-found: ignore

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-reports
          path: build/reports/tests/*
          if-no-files-found: ignore

  build-platforms:
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Gradle build
        run: ./gradlew build

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-results-java${{ matrix.java }}-${{ matrix.os }}
          path: build/test-results/**/TEST-*.xml
          if-no-files-found: ignore

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-reports-java${{ matrix.java }}-${{ matrix.os }}
          path: build/reports/tests/*
          if-no-files-found: ignore

    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
        os:
          - ubuntu-16.04
          - macos-latest
          - windows-latest
        include:
          - java: 15
            os: ubuntu-latest
